spring:
  application:
    name: DemoClient

server:
  port: 85

eureka:
#  password: password
  client:
    serviceUrl:
      # 这里配置eureka地址
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}

weaver:
  provider:
    name: ecology-workflow-service

feign:
  circuitbreaker:
    enabled: true

endpoints:
  restart:
    enabled: true